jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yVGVzdHMxMjM0NTY3ODkw

services.auth-service=http://localhost:9999
services.order-service=http://localhost:9998
services.delivery-service=http://localhost:9997
services.inventory-service=http://localhost:9996
services.notification-service=http://localhost:9995

logging.level.org.springframework.web.cors=TRACE
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG